PROJECT_ID: PVT_kwDOAKeGAM4BMhtd
STATUS_FIELD_ID: PVTSSF_lADOAKeGAM4BMhtdzg7yKds
PRIORITY_FIELD_ID: PVTSSF_lADOAKeGAM4BMhtdzg7yKvk
STATUS_OPTION_IDS:
  Backlog: f75ad846
  Ready: 61e4505c
  In progress: 47fc9ee4
  In review: df73e18b
  Done: '98236657'
PRIORITY_OPTION_IDS:
  P0: '79628723'
  P1: 0a877460
  P2: da944a9c
